### ISSUE TITLE
Ability to split by both policy and calendar years simultaneously

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#20]
Is this something that has any benefit? The main use case I can think of is doing both policy and calendar year aggregations on the same dataframe. But I suppose these aggregations can be done with two dataframes.

Unsure if it is possible to an analysis on both simultaneously (grouping by both policy years and calendar years) because there would be so much truncation.

Is this feature worth the effort and additional complexity?

**Comment by mattheaphy** [comment]
It might be useful for some folks. I've done an implementation of this in the past. The upside is a single data frame as you said. The downside is that it can lead to confusion or incorrect assumptions about exposures, especially when the decrement of interest is fully exposed. 

Let's keep this issue open as something to look at in the future.
