### ISSUE TITLE
include end date for intervals in exposure dataframe

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#21]
Main motivation for the issue is that it helps implement https://github.com/mattheaphy/actxps/issues/7

There is an Rcpp algorithm for assigning transactions to date intervals that uses end dates of intervals.

It is maybe possible to implement this by determining the policy year of the transactions, but I imagine some complexities if https://github.com/mattheaphy/actxps/issues/20 gets implemented or maybe dealing with truncation dates.

edit: any input on what the right approach is for https://github.com/mattheaphy/actxps/issues/7 and the inclusion of end dates on exposures?

**Comment by mattheaphy** [comment]
Thanks! There's a large update to dplyr that was released this week that allows for rolling and overlapping joins. I think this might be an ideal candidate for #7. However, that will require an end date as well. I can look to add this. 

I'll also look at the Rcpp algorithm to see how it compares to using dplyr.
