### ISSUE TITLE
Date of lapse may need back dating if on policy anniversary

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#22]
section 4.3 of the Society of Actuaries (SOA) [experience study document](https://www.soa.org/49378a/globalassets/assets/files/research/experience-study-calculations.pdf) states that 

> For a lapse on a policy anniversary, using 11:59 pm on the day before the anniversary assures that the lapse is allocated to the proper policy year.

https://www.actuarialopensource.org/actxps_experienceanalysis_2023_02_03.html#term-is-anniv

**Comment by mattheaphy** [comment]
I agree with the sentiment, but disagree there's an issue here. The package should not make assumptions about the accuracy of input data. The user of package should ensure the data they're supplying data that is fit for purpose.

There are also practical challenges with attempting to build this feature. One would have to prescribe or guess at policy status values / codes, and those should be expected to vary greatly by user.
