### ISSUE TITLE
Partial exposures not created starting at a left truncation date

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#23]
https://www.actuarialopensource.org/actxps_experienceanalysis_2023_02_03.html#left-trunc

**Comment by mattheaphy** [comment]
This was a design choice. There is no left-censoring of policy duration exposures in the package. A couple of reasons for this:

- Left-censoring mildly complicates the calculation of exposures, especially when there is a termination (should the exposure be 100% or 100% of the time spanning from the start date to the next anniversary?).
- Results are easier to interpret when every exposure record spans a complete policy duration versus the alternative of the first period not spanning a full period.
- If we want to add an additional period, a simple solution is to roll back the starting period to an earlier date.

**Comment by MatthewCaseres** [comment]
Thank you, I found a reference for this in section 10.2.1 of the [experience studies document](https://www.soa.org/49378a/globalassets/assets/files/research/experience-study-calculations.pdf) and this issue is not actually an issue.

Issue is raised in ExperienceAnalysis.jl package so that there can be consistency with the approach you are taking.

Is the exclusion of partial rate intervals on the right truncation something that is necessary? If yes, is it currently being done?

**Comment by mattheaphy** [comment]
I don't think that's necessary. In my experience, most people want to keep partial exposures in the last period. I generally think that's a good idea, especially since it's common practice to fully expose the decrement of interest.

**Comment by MatthewCaseres** [comment]
Thank you for your advice, it seems this is discussed in section 17.6.4 of the experience studies document.
