### ISSUE TITLE
Policies issued on leap year do not create exposures on non-leap years

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#25]
https://www.actuarialopensource.org/actxps_experienceanalysis_2023_02_03.html#leap

**Comment by mattheaphy** [comment]
I noticed that this morning as well. It's a more general problem of days ending in 29-30 (in the case of February) or 31 (Feb, Apr, Jun, Sept, Nov). I'm putting in a fix to the expose function and creating a new unit test for this.
