### ISSUE TITLE
docs site

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#8]
should there be a docs site?

**Comment by mattheaphy** [comment]
Are you talking about creating a GitHub pages site? If so, that's something I'd like to do. I want to write up a proper vignette.

**Comment by MatthewCaseres** [comment]
Ok cool. I opened this issue cause I didn't know if it was on your radar.

For the things you'd like to do it might make sense to open your own issues in the repo so that others can see what features you are planning, maybe help you organize your own thoughts as well.

**Comment by mattheaphy** [comment]
Add pkgdown site on GitHub pages.
